spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/sim_db}
    username: ${DB_USERNAME:sim_user}
    password: ${DB_PASSWORD:sim_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
